name: License Scan
on: [pull_request, push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run License Checker
        run: npx license-checker --summary --onlyAllow="MIT;ISC;BSD-3-Clause;Apache-2.0;Zlib;Libpng"